# Generated by Django 4.2.4 on 2023-08-06 15:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Наименование')),
                ('description', models.TextField(blank='True', null='True', verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Наименование')),
                ('description', models.TextField(blank='True', null='True', verbose_name='Описание')),
                ('image', models.ImageField(blank='True', null='True', upload_to='products/', verbose_name='Изображение')),
                ('price', models.IntegerField(blank='True', null='True', verbose_name='Цена')),
                ('date_creation', models.DateField(verbose_name='Дата создания')),
                ('date_changing', models.DateField(verbose_name='Дата изменения')),
                ('category', models.ForeignKey(blank='True', null='True', on_delete=django.db.models.deletion.CASCADE, to='catalog.category', verbose_name='id категории')),
            ],
            options={
                'verbose_name': 'Продукт',
                'verbose_name_plural': 'Продукты',
                'ordering': ['category', 'name'],
            },
        ),
    ]
