# Generated by Django 4.2.4 on 2023-08-19 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=100, verbose_name='Наименование')),
                ('category_description', models.TextField(verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=100, verbose_name='Наименование')),
                ('product_description', models.TextField(verbose_name='Описание')),
                ('product_image', models.ImageField(blank=True, null=True, upload_to='products/', verbose_name='Изображение')),
                ('product_category', models.CharField(max_length=50, verbose_name='Категория')),
                ('product_price', models.IntegerField(verbose_name='Цена')),
                ('create_date', models.DateField(verbose_name='Дата создания')),
                ('change_date', models.DateField(blank=True, null=True, verbose_name='Дата изменения')),
            ],
            options={
                'verbose_name': 'Продукт',
                'verbose_name_plural': 'Продукты',
            },
        ),
    ]
